services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/t-cnica
    ports:
      - "3000:3000"
    depends_on:
      - db
  redis:
    image: redis:alpine
    command: redis-server --appendonly yes
    volumes:
      - ./tmp/redis:/data
    ports:
      - "6379:6379"
  sidekiq:
    build: .
    command: bundle exec sidekiq
    volumes:
      - .:/t-cnica
    depends_on:
      - db
      - redis